bank_info:
    title: Motion in 1D with constant acceleration (2-back-to-back segments)
    bank_id: EXP-PB1-EXMPLPB-01012026 #Subject-Unit-Abbreviation_of_title_or_any_string-date
    description: |-
      Problem set for back to back segments of UAM along 1D.
    date created: 09-18-2025 # Today's date 
    learning objectives:
        - 1DM-KE-1
    generation prompts: # The following are the prompts that generated the questions in the problem bank.
        - prompts: "./prompts.md"  
        - formatting prompt: "./YAML_formatting_prompt.md" #modify as needed.
    generation details: # Details of the creation process
            model: GPT-5 # The model used to generate the questions
    authors:
        - O. Moussa